### ISSUE TITLE
[BUG] Wrong .NET version

### ISSUE THREAD

**Issue by Octogeisha** [VirtualZer0/TwitchKeyboard#5]
**Bug description | Краткое описание**

**How to reproduce | При каких условиях появляется**

**Expected behavior | Как это должно работать правильно**

**Content from crashlog.txt | Содержимое crashlog.txt**

**Additional infromation | Дополнительная информация**

**Comment by Octogeisha** [comment]
after installing  first  step  . NET  TASK https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.101-windows-x64-installer ( THE  UPDATED INSTALL) 

with the most  up to date  twitch keyboard   [Twitch Keyboard v1.0.3 RC 2] (https://github.com/VirtualZer0/TwitchKeyboard/releases/tag/1.0.3-rc.2)

i then  put  in  cmd thing dotnet   
to  confirm and verify  as suggested 

but  every  time i try  to  load
[Twitch Keyboard v1.0.3 RC 2]  this  message  appears 

- You must install or update .NET to run this application.

Framework: 'Microsoft.WindowsDesktop.App', version '6.0.0' (x64)


so installed 6.0.0  and  same message appears ?

**Comment by VirtualZer0** [comment]
![image](https://user-images.githubusercontent.com/45962846/210029219-6c940f5b-f154-4dea-a5c4-579d3a9472a1.png)

You are downloading the wrong version. What you need is the .NET Desktop Runtime.

**Comment by Octogeisha** [comment]
following this  advice i uninstalled all  .net  things  so they  didnt  combat  each other   and   just downloaded (windowsdesktop-runtime-7.0.1-win-x64)   i go  to run the programme  i know have this!  
![Untitled](https://user-images.githubusercontent.com/85520720/210074468-90f5a510-3cbd-4928-b3ae-aeed9fdf4520.png)

i did  also type in the cmd this 

![Untitled](https://user-images.githubusercontent.com/85520720/210074808-d9a8902d-921f-4c7b-bf7e-a9892454a114.png)

what i am i doing wrong ?

**Comment by Octogeisha** [comment]
also thankyou for taking time to respond and help

**Comment by VirtualZer0** [comment]
Sorry, I gave a little wrong information. .NET 7 will be needed for the next version of the program, which has not yet been released. You need .NET 6 Desktop Runtime. That said, you do not have to uninstall .NET 7, it will not interfere with your work and you will not have to install it again after the new version.

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.12-windows-x64-installer

**Comment by Octogeisha** [comment]
okay  so i downloaded this  i still get 
![210074468-90f5a510-3cbd-4928-b3ae-aeed9fdf4520](https://user-images.githubusercontent.com/85520720/210087483-5a573cc8-98a2-465b-81d5-3f3d56f91435.png)

**Comment by VirtualZer0** [comment]
This is a strange situation. Did you download the .NET 6 Desktop Runtime specifically? Try to install all possible variants of .NET 6

**Comment by Octogeisha** [comment]
just the  .NET 6 Desktop Runtime

**Comment by Octogeisha** [comment]
-_-

**Comment by VirtualZer0** [comment]
Try this version 
https://github.com/VirtualZer0/TwitchKeyboard/releases/download/1.0.3-rc.2/TwitchKeyboard.x64.standalone.zip

**Comment by VirtualZer0** [comment]
I will mark this issue as solved for now, if the problem still persists, reopen it or create a new one.

**Comment by Octogeisha** [comment]
its downloaded app loaded   but  isnt  connecting  with twitch

**Comment by VirtualZer0** [comment]
I think this is an issue related to bug #6. Try checking the versions I posted to the thread in the issue I mentioned.
